# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mi_servicio_pb2 as mi__servicio__pb2


class MiServicioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Saludar = channel.unary_unary(
                '/mi_paquete.MiServicio/Saludar',
                request_serializer=mi__servicio__pb2.SaludoRequest.SerializeToString,
                response_deserializer=mi__servicio__pb2.SaludoResponse.FromString,
                )


class MiServicioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Saludar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MiServicioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Saludar': grpc.unary_unary_rpc_method_handler(
                    servicer.Saludar,
                    request_deserializer=mi__servicio__pb2.SaludoRequest.FromString,
                    response_serializer=mi__servicio__pb2.SaludoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mi_paquete.MiServicio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MiServicio(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Saludar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mi_paquete.MiServicio/Saludar',
            mi__servicio__pb2.SaludoRequest.SerializeToString,
            mi__servicio__pb2.SaludoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
