# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mi_servicio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11mi_servicio.proto\x12\nmi_paquete\"\x1f\n\rSaludoRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\" \n\x0eSaludoResponse\x12\x0e\n\x06saludo\x18\x01 \x01(\t2N\n\nMiServicio\x12@\n\x07Saludar\x12\x19.mi_paquete.SaludoRequest\x1a\x1a.mi_paquete.SaludoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mi_servicio_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SALUDOREQUEST']._serialized_start=33
  _globals['_SALUDOREQUEST']._serialized_end=64
  _globals['_SALUDORESPONSE']._serialized_start=66
  _globals['_SALUDORESPONSE']._serialized_end=98
  _globals['_MISERVICIO']._serialized_start=100
  _globals['_MISERVICIO']._serialized_end=178
# @@protoc_insertion_point(module_scope)
